# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acfd007ee8ebe1e521dac38f60086983234ad161623cd9c2e2d511524eba237e7a8b5ce02712ac83c33f5d4acb376c366bed6a1f9d29b89f8b309deef572676d

test:
  secret_key_base: aa03984491abab28122385c1fd25df855e185f5c9afb2be62d29ef898babec9c58e2565a8a5f2d4a2a4eeba217253ff43560a59164a2f4da8db59ffeb1558a73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
